name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install OpenCV + Clang + LLVM
      run: |
        sudo apt update
        sudo apt install -y \
          clang \
          llvm-dev \
          libclang-dev \
          pkg-config \
          libopencv-dev \
          libgtk-3-dev \
          libxcb-render0-dev \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev \
          libxkbcommon-dev \
          libssl-dev

    - name: Build
      run: cargo build --verbose
