name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Clang + LLVM dependencies
      run: |
        sudo apt update
        sudo apt install -y clang llvm-dev libclang-dev

    - name: Build
      run: cargo build --verbose

